import type { DispatchRequest, Guest, StaffMember } from "./types";

export const SEED_REQUESTS: DispatchRequest[] = [
  {
    id: "req-001",
    department: "housekeeping",
    room: "814",
    summary: "Extra towels and turndown service requested",
    guestName: "Mrs. Chen Wei",
    guestTier: "Pinnacle",
    guestPrefs: "Hypoallergenic bedding, no fragrance",
    priority: "normal",
    status: "pending",
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    eta: "15 min",
    assignedTo: "Ling Chen",
  },
  {
    id: "req-002",
    department: "maintenance",
    room: "502",
    summary: "Air conditioning not cooling below 22°C",
    guestName: "Mr. Harrington",
    guestTier: "Élevé",
    guestPrefs: "Temperature: 19°C preferred",
    priority: "urgent",
    status: "in_progress",
    createdAt: new Date(Date.now() - 28 * 60000).toISOString(),
    eta: "8 min",
    assignedTo: "Raj Patel",
  },
  {
    id: "req-003",
    department: "front_desk",
    room: "1204",
    summary: "Late checkout extension requested until 15:00",
    guestName: "Dr. Amara Osei",
    guestTier: "Pinnacle",
    guestPrefs: "Quiet floor, high level",
    priority: "normal",
    status: "pending",
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    eta: "5 min",
    assignedTo: "Sofia Reyes",
  },
  {
    id: "req-004",
    department: "concierge",
    room: "709",
    summary: "Dinner reservation at Madera for party of 4, tonight 8PM",
    guestName: "Mr. & Mrs. Fontaine",
    guestTier: "Élevé",
    guestPrefs: "Window table, champagne on arrival",
    priority: "normal",
    status: "pending",
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
    eta: "20 min",
    assignedTo: "André Beaumont",
  },
  {
    id: "req-005",
    department: "housekeeping",
    room: "613",
    summary: "Minibar restock — vodka, still water, dark chocolate",
    guestName: "Ms. Ikaika Kahananui",
    guestTier: "Standard",
    guestPrefs: "No dairy products",
    priority: "low",
    status: "pending",
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    eta: "30 min",
  },
  {
    id: "req-006",
    department: "maintenance",
    room: "1101",
    summary: "In-room safe combination reset required",
    guestName: "Baron von Richter",
    guestTier: "Pinnacle",
    guestPrefs: "German-speaking staff preferred",
    priority: "urgent",
    status: "pending",
    createdAt: new Date(Date.now() - 3 * 60000).toISOString(),
    eta: "10 min",
  },
  {
    id: "req-007",
    department: "concierge",
    room: "416",
    summary: "Private car to SFO Terminal 1, tomorrow 6:15AM",
    guestName: "Ms. Priya Nair",
    guestTier: "Élevé",
    guestPrefs: "Tesla or similar EV preferred",
    priority: "normal",
    status: "in_progress",
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    eta: "Confirmed",
    assignedTo: "Yuki Tanaka",
  },
];

export const SEED_GUESTS: Guest[] = [
  {
    room: "814",
    name: "Mrs. Chen Wei",
    tier: "Pinnacle",
    status: "Checked In",
    preferences: "Hypoallergenic, no fragrance, extra firm pillows",
    languages: "Mandarin, English",
  },
  {
    room: "1204",
    name: "Dr. Amara Osei",
    tier: "Pinnacle",
    status: "Checked In",
    preferences: "Quiet floor, high level, plant-based meals",
    languages: "English, French",
  },
  {
    room: "1101",
    name: "Baron von Richter",
    tier: "Pinnacle",
    status: "VIP Arrival",
    preferences: "German-speaking staff, vintage Bordeaux, no phone calls",
    languages: "German, English",
  },
  {
    room: "502",
    name: "Mr. James Harrington",
    tier: "Élevé",
    status: "Checked In",
    preferences: "Cool room (19°C), morning papers, Irish breakfast",
    languages: "English",
  },
  {
    room: "709",
    name: "Mr. & Mrs. Fontaine",
    tier: "Élevé",
    status: "Checked In",
    preferences: "Window table dining, champagne preference, no seafood",
    languages: "French, English",
  },
  {
    room: "416",
    name: "Ms. Priya Nair",
    tier: "Élevé",
    status: "Departing",
    preferences: "EV transfer, vegetarian, early checkout",
    languages: "English, Hindi",
  },
  {
    room: "613",
    name: "Ms. Ikaika Kahananui",
    tier: "Standard",
    status: "Checked In",
    preferences: "No dairy, local artwork interest",
    languages: "English, Hawaiian",
  },
];

export const SEED_STAFF: StaffMember[] = [
  { name: "Sofia Reyes", department: "Front Desk", shift: "07:00 – 15:00" },
  { name: "Marcus Webb", department: "Front Desk", shift: "15:00 – 23:00" },
  { name: "Ling Chen", department: "Housekeeping", shift: "08:00 – 16:00" },
  { name: "Tomás Vega", department: "Housekeeping", shift: "16:00 – 00:00" },
  { name: "Raj Patel", department: "Maintenance", shift: "07:00 – 15:00" },
  { name: "Eliza Fontaine", department: "Maintenance", shift: "15:00 – 23:00" },
  { name: "André Beaumont", department: "Concierge", shift: "09:00 – 18:00" },
  { name: "Yuki Tanaka", department: "Concierge", shift: "18:00 – 02:00" },
];
